GET https://api.spotify.com/v1/me/playlists
Authorization: Bearer BQB3m5hp0T1RjVCX0PLcNAcYqce7cdw4Elh5TMQMrAnfGHxqY7DvH6CrmHLofOvJ2MRW5JHTmjm77KkcTsU3mvV1_JsUupi3Ce_S0S2nh447ss0Q3ZCBR1jkCVyDvwl5B0wW7UPtMSiPaTl14f0F0Mytz32y4ZlfWDaUkAVps8X9f2I6pEzStJBIXOg22atjGNqO_myggjpcQf8yNrPnLgPjwkgDnkRJG6w
